Scenes
rvl-system/home-lights pull request #54
Opened 2020-11-29 23:39 UTC by nebrius

This implements viewing of scenes for each zone in the zones tab. Create, edit, and delete buttons are viewable in edit mode, but currently just log to the console when clicked.

2020-12-08 05:05 UTC, allxie requested changes

2020-12-08 05:05 UTC, allxie commented on client/src/components/scene/editSceneButton.tsx
> +  function handleConfirm(values: Record<string, string>) {
(Chatting offline about implementation of this and create scenes)

2020-12-08 05:16 UTC, nebrius commented on client/src/components/light/createLightButton.tsx
> +      values.zone !== 'off' ? parseInt(values.zone) : undefined
Good thinking, will do

2020-12-08 05:32 UTC, nebrius commented on client/src/components/lib/formInput.tsx
> +  T extends Record<string, string | number>,
This is some kinda fancy TypeScript footwork. I'm exploiting [generics](https://www.typescriptlang.org/docs/handbook/generics.html) to enforce the relationship between stuff.

`T extends Record<string, string>` says that the form input spits data of type `T`, which is supplied by the caller. The extends bit says T can't just be anything though, it must be something that's an object with strings for keys (not numbers, which are actually valid!), and that the value of each property must also be a string.

`K extends keyof T` says there's a second generic parameter that is equal to one of the keys in `T`

So let's say the form is dealing with this data:

```TypeScript
{
  name: string;
  description: string;
}
```

Then `T` is that whole definition, and `K` is `'name' | 'description'`, and `T[K]` means the type of one of the properties (e.g. `string` for `data.name`) while also guarding against accessing a property that doesn't exist.

This utilizes some tricks I learned recently to enforce some extra type checking, even though this code is super dynamic.

2020-12-08 05:38 UTC, nebrius commented on client/src/components/scene/deleteSceneButton.tsx
> +        confirmLabel="Delete light"
Fixed

2020-12-08 05:38 UTC, nebrius commented on client/src/components/light/editLightButton.tsx
> +    options: [{ value: 'off', label: 'Unassigned' }].concat(
Fixed

2020-12-08 05:38 UTC, nebrius commented on client/src/components/light/createLightButton.tsx
> +      values.zone !== 'off' ? parseInt(values.zone) : undefined
Fixed

2020-12-08 06:05 UTC, allxie commented on client/src/components/light/editLightButton.tsx
> +    options: [{ value: 'off', label: 'Unassigned' }].concat(
(There were a few other spots I didn't point out in case you just did these two.)

2020-12-08 07:38 UTC, nebrius commented on client/src/components/light/editLightButton.tsx
> +    options: [{ value: 'off', label: 'Unassigned' }].concat(
I replaced all instances of 'off' with the constant...yay replace all!

2020-12-11 03:04 UTC, allxie approved these changes

2020-12-11 03:05 UTC, merged