Reconcile
rvl-system/home-lights pull request #72
Opened 2020-12-15 18:58 UTC by nebrius

This fills in the missing gaps where updating one part of state wasn't being reflected in other parts of state, such as moving a light from one zone to another needing to remove the light entry from scenes in old zone and adding it to scenes in the new zone.

Fixes #57 and #62

2020-12-16 19:39 UTC, nebrius commented
I went ahead and added null coalescing to fix #59 as part of this PR, since it touched on a lot of the same code

2020-12-19 05:41 UTC, allxie commented on server/src/db/philipsHue.ts
> +      return undefined;
doesn't "return" just return undefined?

2020-12-19 05:41 UTC, allxie commented on server/src/db/scenes.ts
> +  console.log(zones, patterns, lights);
Did you mean to leave this?

2020-12-19 06:15 UTC, nebrius commented on server/src/db/philipsHue.ts
> +      return undefined;
Haha, oh right, will change.

2020-12-19 06:15 UTC, nebrius commented on server/src/db/scenes.ts
> +  console.log(zones, patterns, lights);
Nope, will remove

2020-12-19 19:13 UTC, nebrius commented on server/src/db/philipsHue.ts
> +      return undefined;
Fixed

2020-12-19 19:13 UTC, nebrius commented on server/src/db/scenes.ts
> +  console.log(zones, patterns, lights);
Fixed

2020-12-20 01:47 UTC, allxie requested changes

2020-12-20 01:47 UTC, allxie commented on server/src/device/phillipsHue.ts
> +    return undefined;
Also these, please

2020-12-20 01:52 UTC, nebrius commented on server/src/device/phillipsHue.ts
> +    return undefined;
Done

2020-12-20 01:54 UTC, allxie approved these changes

2020-12-20 01:54 UTC, merged